services:
  # 1. Database Service
  postgres:
    container_name: sport_booking_postgres
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      # Mount data ra ngoài máy thật để tắt Docker không mất dữ liệu
      - ./postgres-data:/var/lib/postgresql/data
    command: >
      -c timezone='UTC'
    networks:
      - sport-booking-network

networks:
  sport-booking-network:
    driver: bridge